from featureSelector import *

dictionary = {
                1 : featureSelector.zeroFeature,
                2 : featureSelector.long_url,
                3 : featureSelector.zeroFeature,
                4 : featureSelector.zeroFeature,
                5 : featureSelector.zeroFeature,
                6 : featureSelector.pref_suf,
                7 : featureSelector.zeroFeature,
                8 : featureSelector.ssl_state,
                9 : featureSelector.zeroFeature,
                10 : featureSelector.zeroFeature,
                11 : featureSelector.zeroFeature,
                12 : featureSelector.https_token,
                13 : featureSelector.zeroFeature,
                14 : featureSelector.url_of_anchor,
                15 : featureSelector.tag_links,
                16 : featureSelector.zeroFeature,
                17 : featureSelector.zeroFeature,
                18 : featureSelector.zeroFeature,
                19 : featureSelector.zeroFeature,
                20 : featureSelector.zeroFeature,
                21 : featureSelector.zeroFeature,
                22 : featureSelector.zeroFeature,
                23 : featureSelector.iframe,
                24 : featureSelector.domain_age,
                25 : featureSelector.zeroFeature,
                26 : featureSelector.zeroFeature,
                27 : featureSelector.zeroFeature,
                28 : featureSelector.zeroFeature,
                29 : featureSelector.links_to_page,
                30 : featureSelector.zeroFeature,
            }
